### ISSUE TITLE
Enum reserved support?

### ISSUE THREAD

**Issue by RachM** [whisklabs/grpc-ts#16]
I tried to run `npx @whisklabs/grpc` on a proto with an Enum with reserved fields (here's the [proto spec](https://developers.google.com/protocol-buffers/docs/proto3#reserved_values)), and I received an error:

```
Thrower {
  name: 'enum value',
  message: [
    [ 'Token "1" not equal "="', 1 ],
    [ 'Token ";" not equal "number"', 2 ],
    [ 'Token "reserved" not equal ";,["', 3 ],
    [ 'reserved, 1, ;, reserved, ;', 0 ]
  ],
  line: 4,
  column: 12,
  range: [
    'reserved',      '1',
    ';',             'reserved',
    '"ANIMAL_BIRD"', '...',
    'ANIMAL_DOG',    '=',
    '3',             ';',
    '}'
  ]
}
```

It looks like the reserved field is not supported in the enum parser? Here's a simple example illustrating it:
```
syntax = "proto3";

enum Animal {
  ANIMALUNSPECIFIED = 0;
  ANIMAL_CAT = 2;
  ANIMAL_DOG = 3;
  reserved 1;
  reserved "ANIMAL_BIRD";
}
```
And run `PROTO_DIR=./ PROTO_OUT=whisk npx @whisklabs/grpc`

**Comment by kot9ta** [comment]
Hi @RachM, Enum reserved support was added in [v1.1.2](https://github.com/whisklabs/grpc-ts/releases/tag/v1.1.2)
